const EMPTY_NUMBER = 0;
const WHITE_NUMBER = 1;
const BLACK_NUMBER = 2;
const AVAILABLE_NUMBER = 3;

const WHITE_COLOR = 'white';
const BLACK_COLOR = 'black';

const DESK_SIZE = 8;

const FLIP_ITERATIONS = 20;
const FLIP_ITERATIONS_INTERVAL = 25;
const CANVAS_SAGE_PIXELS_COUNT = 1;

const PASS_TURN = 'PASS_TURN';

module.exports = {
  EMPTY_NUMBER,
  WHITE_NUMBER,
  BLACK_NUMBER,
  AVAILABLE_NUMBER,
  WHITE_COLOR,
  BLACK_COLOR,
  DESK_SIZE,
  FLIP_ITERATIONS,
  FLIP_ITERATIONS_INTERVAL,
  CANVAS_SAGE_PIXELS_COUNT,
  PASS_TURN,
};